#  __         ______     ______     ______
# /\ \       /\  ___\   /\  __ \   /\  ___\
# \ \ \____  \ \  __\   \ \  __ \  \ \  __\
#  \ \_____\  \ \_____\  \ \_\ \_\  \ \_\
#   \/_____/   \/_____/   \/_/\/_/   \/_/
#
# Author : Smudge

# --- Changing these values requires a proxy restart. ---
enabled: true
debugmode: false

# SQLITE DATABASE
type: SQLITE

# # MONGO DATABASE
# connection_string: "connectionString"
# database_same: "Database"

# The maximum amount of history that will
# be saved in the database per player.
player_history_limit: 20

# The maximum number of messages that will
# be saved in the database per player.
message_limit: 100